hash-format = "sha256"

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "94a719c6336dce30b5092d4241a49e6739b03959bd59da9babf5b2d22b028890"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c784cee4a8eed3f2b36172b8c5a119a62a28880d15e7f169947c935bf3bf4bb3"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "d3237427c060742b9b724e0a65d57074c430f06d4f3dadf857ea5252602c8fe4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "75e935b63073ad2104c50baead0898b07ff60c0f465adf796f4a4960db8eae09"
metafile = true

[[files]]
file = "mods/minecraft-comes-alive-7.6.13+1.20.1-universal.jar"
hash = "b50b8fd0cc3a3e8247d5bc120dfe132eade1edc02e99458b6e008bfc6b40aecc"

[[files]]
file = "mods/naturalist.pw.toml"
hash = "b852615d05a8e25c2a84af3443e25fcd46e7a0d996ddbf3c0c860928846f1f40"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "356a264757b1b5d0eda01c8c09ec7dd40062e93003d1e5ee027d3215eef2e0ce"
metafile = true
