hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "ea430db88d8f190a053e4f3c662d2a59b6a7508778525034f2b20037ee074aec"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "7b9bcc299b6587626d256c571fc122e6147d8d760cb7056d537c88cce5d993f9"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "45d8570e9c13f5265d9d833ba2431e982ab9cf2760e86c6d5fd62dd3c092e18c"
metafile = true

[[files]]
file = "mods/architectury-9.2.14-fabric.jar"
hash = "bd7a7032bedb2ff96c6991a846a44c857336a51442a105f5859017e8ba9d1321"

[[files]]
file = "mods/armor-3d.pw.toml"
hash = "77f0a8eac3c518ffa9ee8cff01132befab7bcefb190406cb14c28b0a420bee53"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "d6878871a07870b33821beed20118368e779c17574062d5d771eb38b9403e875"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
hash = "360c50d7131402e9dd322ec73da30715be320f35a0376768952e622e24e75bd1"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "1173755b093b4f9a8aca00520d87bc35178fe19c54e59debe5c48d0c9063b91c"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b1581bbfae9d16690f4022536da6567f000130c4ea5e04d92177c1bc61fea709"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "ae11fe7c63207b7257ecb782d421655c6f56adb551b78ad430066edc94bee3b1"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "d47260d085f9c59609bbc7582968e60f4c476d934c815142360bbcc4b5113a4d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e81c635602878f92af9a9c11b92481b25c7aaf3f68cd015dabf5f67201886401"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "4fd70be0bf3cf24f707d5347c7db0bffde9c000cfa72bb1994ba6632e68bc7e0"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "94a719c6336dce30b5092d4241a49e6739b03959bd59da9babf5b2d22b028890"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "af83eb1ea0f7a36e4424248c744c1cbebb5045d361e843b873d4d89bf65ad8ad"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "6ec7fc70c84dc7f7f4578a85480264d82336d64ac0d8c95c0fcc55d350f64ab7"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c5ea75feae4d340856611f78a29e6f1f0b7e707bfe43847f11d25fac1769dee7"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "0bcc0df994ebbe98efc2f87c653cd0ae0a81bb0ca47b5adacba0974c5c6406c5"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "fec1ffa03b4d62e47be25512840490844fc383cf82d2ad35345b2f87a21e8228"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "b13f84a7fad7d6e21cef513a9c8f8206e55f0b342b4030df540e3126ad5abb2a"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "85e012f1e3fa929ed32f3ce347c9f26606e80393ed30988553a656fd8003900b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "fff1e00559f13c092b17fa83804279cf70191d7a99a4a98a4eb6bb30ac9a78db"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "d3237427c060742b9b724e0a65d57074c430f06d4f3dadf857ea5252602c8fe4"
metafile = true

[[files]]
file = "mods/hold-my-items.pw.toml"
hash = "e848d17092a61b91d0198361cc333fb5d3912cdb5bb561f0520f2f87a75db6e6"
metafile = true

[[files]]
file = "mods/immersive-hotbar.pw.toml"
hash = "a4b6a816a2c211691e9447bd6e5c8a3485da3e5926b0212d26cdb95514ddaa92"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "60adfc1ee75f10a7290e18f3e2b82601a3d3915db0c53dabe08dd17daf1c7d76"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/item-interactions-mod.pw.toml"
hash = "2c960f14667a177c575bf1ea5b6ed5646316e99f04bc33c1dbe329cbccce8a6d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "75e935b63073ad2104c50baead0898b07ff60c0f465adf796f4a4960db8eae09"
metafile = true

[[files]]
file = "mods/lithosphere.pw.toml"
hash = "11e8f7c2a2214f3133188ca8d045c9171eca8988fbae8a13572e56129b8b9910"
metafile = true

[[files]]
file = "mods/minecraft-comes-alive-7.6.13+1.20.1-universal.jar"
hash = "b50b8fd0cc3a3e8247d5bc120dfe132eade1edc02e99458b6e008bfc6b40aecc"

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "10430695ad67fd14a9e208c0ebe6efaf073cc78e3292f52159b2d04b75b87214"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
hash = "b852615d05a8e25c2a84af3443e25fcd46e7a0d996ddbf3c0c860928846f1f40"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "d68efcc17365557a070fbfe07c1523c041f3c9c41eb637beace220d2c13c849c"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
hash = "63a2011c75cdaf07c0a537c1f5c0661b7e5e0471c81625273634f88fed05b9c4"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "a9769ced0531122518321833966d375196753db1c3a47b975aed4bb6837fae7a"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "830270b8e5a34f5621720ae09c4cf716a65d8003a30d585c8b817aba1fde9ac8"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "fae2bc6c282159f6a2e55e22d19241c625a9795dddbe8bd0f0b501c8aa709be1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "356a264757b1b5d0eda01c8c09ec7dd40062e93003d1e5ee027d3215eef2e0ce"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5cd3420078c7c24bf7414c7243a69b2d2a21c3c5e29150444697b11a001c44d8"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "e53888490a33ad3127b09dd98ce001e579cb6c205a99a1e6e0424ab9f5b862c2"
metafile = true

[[files]]
file = "mods/still-life.pw.toml"
hash = "79129a6a9c3832ca239d2903cf7fa92b413d16929b98e4b10e19b50f4856fb4a"
metafile = true

[[files]]
file = "mods/sushi-bar.pw.toml"
hash = "6bfb09a5bf731cd8d347b8e77b0379c254b2e2dd2763c8051b6bfe122a22b7fb"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "72c0e1d4d8eb05e6c82c8959885ee5f08b8c7ede63b438e22a7422246679cc46"
metafile = true

[[files]]
file = "mods/vectorientation.pw.toml"
hash = "5bba63e855efd5e7249461bf210c21b4da30590c62a93f1d40704e978500f2b1"
metafile = true

[[files]]
file = "mods/vivecraft-compat.pw.toml"
hash = "a99fe3eb35cf411364bd89b9dc38c5b3dd033ef6c1e68eac88a1a255d39c1fa8"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
hash = "29c797078c75535e95403bbb351e779371bdc817788e2d043760b4852d87160a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "resourcepacks/canoe-boats.pw.toml"
hash = "b06009e908d0de2ecf73c8d54815980f253a4c2346381acce016291aee870908"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "d3571c12bae3b4ff244307f5f5bdfa1654175981eeda8d76059266eaa7d926fa"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "42b8a59616b3ed15a02e55466dff7ab400d481a8730949ce0168a927b71b91fb"
metafile = true

[[files]]
file = "resourcepacks/gentler-weather-sounds.pw.toml"
hash = "907d76d306276636447fbb12f86d4771646278d35cf2bb24c44e015336713931"
metafile = true

[[files]]
file = "resourcepacks/simple-grass-flowers.pw.toml"
hash = "bc4dcbd6b77adb2180049d63ed4a8981553f06dbf3e32080022ffd87dd1fb09b"
metafile = true
