name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94fe5c9eaf844d5c752c768845d82380b78b3a60b91e346d82c3c4c15a15a227"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
