name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45445c0be8fc159dd27acd14bcba69d699473c7bee09f5181019589f91eed3ea"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
