name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c00985e2f6c6181414966f0b2fb3b3cb7f9756a967e2e591dbc5444552218f01"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
