name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed4609f97c224a876edab282ac2e561d7023e0e9a41af0e0c2c37cc95eb200e4"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
