name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8bcfe0ba1e2af1d7229b7252d6ce19c2557389e671b37e4c2fee95dc7c0e9e4"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
