name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d8c1b7e22571b77a35854d1f3bc21cc0bce786ca3b85b67bc152e632de1e030"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
