name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae3ab78168f168850241b5f018d0e47adde4243552ac613d5d6b319789f67a42"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
