name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b8fc4a53803f708e6ae56511690a68aee03c55027a8a16d3f45791d35295d27"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
