name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ac8a5e8cdfe4b2547110149f6f1444625121b33c24631afcbd064dda82dcc5a"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
