name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f216ac2603ae0d4e811c2e67658ec3813381e9aa7258f30ba29ff8f5da29e044"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
