name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6baf763b08b2bc65a730687884c993cdead20fd0b5c8a113e8f69fb65013bf49"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
