name = "FresitaLand 3: El Nuevo Mundo"
author = "Falisan & Masked"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a36e9217643d5886a4a3b235c9f10fc015e3a8414a85f43cd4d67b1aeef396f6"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
